######################################################################
##
## Filename: cpu_test.udo
## Created on: Fri Jun 03 19:16:44 CST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
